export const GET_ALL_CURRENCIES = 'GET_ALL_CURRENCIES';
export const GET_ALL_CURRENCIES_SUCCESS = 'GET_ALL_CURRENCIES_SUCCESS';
export const GET_ALL_CURRENCIES_FAILURE = 'GET_ALL_CURRENCIES_FAILURE';
