export const GET_TOTAL_MARKET_CAP_DAY = 'GET_TOTAL_MARKET_CAP_DAY';
export const GET_TOTAL_MARKET_CAP_WEEK = 'GET_TOTAL_MARKET_CAP_WEEK';
export const GET_TOTAL_MARKET_CAP_MONTH = 'GET_TOTAL_MARKET_CAP_MONTH';
export const GET_TOTAL_MARKET_CAP_YEAR = 'GET_TOTAL_MARKET_CAP_YEAR';

export const GET_TOTAL_MARKET_CAP_DAY_SUCCESS =
  'GET_TOTAL_MARKET_CAP_DAY_SUCCESS';
export const GET_TOTAL_MARKET_CAP_WEEK_SUCCESS =
  'GET_TOTAL_MARKET_CAP_WEEK_SUCCESS';
export const GET_TOTAL_MARKET_CAP_MONTH_SUCCESS =
  'GET_TOTAL_MARKET_CAP_MONTH_SUCCESS';
export const GET_TOTAL_MARKET_CAP_YEAR_SUCCESS =
  'GET_TOTAL_MARKET_CAP_YEAR_SUCCESS';
